/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class NovahealthPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(_ -> System.out.println("Hello from plugin 'org.example.greeting'"));
        });
    }
}
